name: Node.js CI
on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      INDEXING_BLOCK_RANGE: 10
      STARTING_BLOCK: 21822210
      CHAIN_ID: 31337
      CHAIN_RPC: http://127.0.0.1:8545/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run validate
      - run: npm run test
