name: Node.js CI
on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      INDEXING_BLOCK_RANGE: 10
      STARTING_BLOCK: 21822210
      CHAIN_ID: 31337
      CHAIN_RPCS: http://127.0.0.1:8545
      WALLET_PKS: 0x0000

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Generate prisma types
        run: npm run prisma:generate

      - name: Run Linter
        run: npm run validate

      - name: Run Unit Tests
        run: npm run test
